create database retailsales;
use retailsales;

select @@hostname;

-- change the data type (int to varchar)
alter table brands modify brand_id varchar(20);
alter table categories modify category_id varchar(20);
alter table customers modify customer_id varchar(30);
alter table order_items modify order_id varchar(30);
alter table order_items modify item_id varchar(30);
alter table order_items modify product_id varchar(30);
alter table orders modify order_id varchar(30);
alter table orders modify customer_id varchar(30);
alter table orders modify store_id varchar(30);
alter table orders modify staff_id varchar(30);
alter table products modify product_id varchar(30);
alter table products modify brand_id varchar(30);
alter table products modify category_id varchar(30);
alter table staffs modify staff_id varchar(30);
alter table staffs modify store_id varchar(30);
alter table staffs modify manager_id varchar(30);
alter table stocks modify store_id varchar(30);
alter table stocks modify product_id varchar(30);
alter table stores modify store_id varchar(30);
drop table orders;
drop table order_items;
-- add primary key 
alter table brands add constraint new_constraint primary key(brand_id);
alter  table  categories add constraint new_constraint primary key(category_id);
alter table customers add constraint new_constraint primary key(customer_id);
alter table orders add constraint new_constraint primary key(order_id);
alter table products add constraint new_constraint primary key(product_id);
alter table staffs add constraint new_constraint  primary key(staff_id);
alter table stores add constraint new_constraint primary key(store_id);

-- add foreign key
alter table order_items add constraint new_constraint foreign key(order_id) references orders(order_id);
alter table  order_items add constraint fk_constraint foreign key(product_id) references products(product_id);
alter table orders add constraint fk_cust_constraint foreign key(customer_id) references customers(customer_id);
alter table orders add constraint fk_store_constraint foreign key(store_id) references stores(store_id);
alter table orders add constraint fk_staff_constraint foreign key(staff_id) references staffs(staff_id);
alter table products add constraint fk_cate_constraint foreign key(category_id) references categories(category_id);
alter table products add constraint fk_brand_constraint foreign key(brand_id) references brands(brand_id);
alter table staffs add constraint fk_storeid_constraint foreign key(store_id) references stores(store_id);
alter table stocks add constraint fk_stor_constraint foreign key(store_id) references stores(store_id);
alter table stocks add constraint fk_product_constraint foreign key(product_id) references products(product_id);

-- 3. Join orders, order_items, and products to display detailed line items.
select o.order_id, p.product_id, p.product_name, oi.quantity, oi.list_price, (oi.quantity*oi.list_price) as total_price from orders 
as o inner join order_items as oi on o.order_id= oi.order_id inner join products as p on p.product_id=oi.product_id;

-- 4. Write a query to group sales (total_price) by each store_id. 
select o.store_id,sum(oi.quantity*oi.list_price) as total_price from orders as o inner join order_items as oi on o.order_id=oi.order_id 
group by store_id;

-- 5. Use ORDER BY and LIMIT to get the top 5 most sold products by quantity. 
select order_id, product_id, product_name, quantity,list_price from order_items order by quantity desc limit 5;

-- 6. For each customer, return total orders placed, total items purchased, and total revenue. 
select o.customer_id, count(oi.order_id) as total_orders_placed,sum(oi.quantity)as total_items, sum(oi.quantity * oi.list_price) as total_revenue 
from order_items as oi inner join orders as o on oi.order_id=o.order_id group by customer_id;

-- 7. Write a query to classify customers into spending brackets (e.g., low, medium, high). 
select o.customer_id, sum(oi.quantity*oi.list_price)as total_spending,  
case 
when sum(oi.quantity*oi.list_price)<5000 then 'Low'
when  sum(oi.quantity*oi.list_price) between 5000 and 12000 then 'Medium' 
else 'High' 
end as category
from order_items as oi inner join orders as  o on oi.order_id=o.order_id group by o.customer_id;

-- 8.Analyze total revenue generated by each staff member based on their handled orders. 
select o.staff_id, sum(oi.quantity*oi.list_price) as total_revenue from orders as o 
inner join order_items as oi on o.order_id=oi.order_id group by o.staff_id;

-- 9. Write a query to list products where stock quantity < 10 in any store. 
select s.product_id, p.product_name, s.quantity from stocks as s inner join products as p on s.product_id=p.product_id where quantity<10;

-- 10. Create a table customer_segments that will be populated from Python ML results later. 
select * from customer_segments;

select* from orders;

select * from retailsales.brands;
select * from retailsales.categories;
select * from retailsales.customer_segments;
select * from retailsales.customers;
select * from retailsales.order_items;
select * from retailsales.orders;
select * from retailsales.products;
select * from retailsales.staffs;
select * from retailsales.stocks;
select * from retailsales.stores;

select count(product_id) from products;